name: Kotlin Lint

on:
  push:
    branches:
      - master  # Adjust this branch name as needed
  pull_request:
    branches:
      - master  # Adjust this branch name as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'  # Adjust the Java version as needed

      - name: Install Ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/latest/download/ktlint
          chmod +x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run Ktlint
        run: ktlint --verbose

